/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author mauro-bh-jr
 */
public class menuLivraria extends javax.swing.JFrame {

    /**
     * Creates new form menuLivraria
     */
    public menuLivraria() {
        initComponents();
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        jlblHora.setText(now.format(formatter));
        //jlblHoraNow.setText(now);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jlblHora = new javax.swing.JLabel();
        jlblOlhosdaLotusTitleWhite = new javax.swing.JLabel();
        jlblOlhosdaLotusTitleDark = new javax.swing.JLabel();
        jlblOlhosdaLotusTitleBlue = new javax.swing.JLabel();
        jbtnPainelCRUD = new javax.swing.JButton();
        jbtnPainelVenda = new javax.swing.JButton();
        jlblLotusLogoIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Livraria Olhos da Lótus");
        setBackground(new java.awt.Color(102, 0, 102));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 600));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblHora.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jlblHora.setForeground(new java.awt.Color(255, 255, 255));
        jlblHora.setText("25/07/2022 00:12:31");
        jDesktopPane1.add(jlblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jlblOlhosdaLotusTitleWhite.setFont(new java.awt.Font("Palace Script MT", 3, 60)); // NOI18N
        jlblOlhosdaLotusTitleWhite.setForeground(new java.awt.Color(255, 255, 255));
        jlblOlhosdaLotusTitleWhite.setText("Olhos da Lótus");
        jDesktopPane1.add(jlblOlhosdaLotusTitleWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jlblOlhosdaLotusTitleDark.setFont(new java.awt.Font("Palace Script MT", 3, 62)); // NOI18N
        jlblOlhosdaLotusTitleDark.setForeground(new java.awt.Color(51, 0, 51));
        jlblOlhosdaLotusTitleDark.setText("Olhos da Lótus");
        jDesktopPane1.add(jlblOlhosdaLotusTitleDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jlblOlhosdaLotusTitleBlue.setFont(new java.awt.Font("Palace Script MT", 3, 61)); // NOI18N
        jlblOlhosdaLotusTitleBlue.setForeground(new java.awt.Color(51, 0, 153));
        jlblOlhosdaLotusTitleBlue.setText("Olhos da Lótus");
        jDesktopPane1.add(jlblOlhosdaLotusTitleBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jbtnPainelCRUD.setBackground(new java.awt.Color(102, 102, 255));
        jbtnPainelCRUD.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jbtnPainelCRUD.setForeground(new java.awt.Color(204, 204, 204));
        jbtnPainelCRUD.setText("Painel de Informações");
        jbtnPainelCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPainelCRUDActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbtnPainelCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 260, 60));

        jbtnPainelVenda.setBackground(new java.awt.Color(102, 102, 255));
        jbtnPainelVenda.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jbtnPainelVenda.setForeground(new java.awt.Color(204, 204, 204));
        jbtnPainelVenda.setText("Painel de Venda");
        jDesktopPane1.add(jbtnPainelVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 260, 60));

        jlblLotusLogoIcon.setFont(new java.awt.Font("Liberation Sans", 0, 13)); // NOI18N
        jlblLotusLogoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/lotusLogo.png"))); // NOI18N
        jDesktopPane1.add(jlblLotusLogoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPainelCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPainelCRUDActionPerformed
        // TODO add your handling code here:
        
        Object[] infoPannelOptions = {"Buscar cadastro",
            "Listar cadastros",
            "Novo cadastro",
            "Alterar cadastro",
            "Remover cadastro"};
        int nCRUDoption = JOptionPane.showOptionDialog(null, //evt, title, WIDTH, HEIGHT, icon, infoPannelOptions, EXIT_ON_CLOSE)
        "                                                           Bem vindo ao Painel de gerenciamento.\n                                                                 Selecione a Operação desejada",
        "Painel gerenciador de Cadastros",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.PLAIN_MESSAGE,
        null,//do not use a custom Icon
        infoPannelOptions,//the titles of buttons
        infoPannelOptions[4]);//default button title
        
        switch (nCRUDoption){
            case 0:{
                System.out.println("Buscar cad");
                break;
            }
            case 1:{
                System.out.println("List cad");
                break;
            }
            case 2:{
                System.out.println("List cad");
                break;
            }
            case 3:{
                System.out.println("List cad");
                break;
            }
            case 4:{
                System.out.println("List cad");
                break;
            }
             default:
               {
               JOptionPane.showMessageDialog(null,"WRONG INPUT");
               break;
               }
        }
        
        
    }//GEN-LAST:event_jbtnPainelCRUDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuLivraria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton jbtnPainelCRUD;
    private javax.swing.JButton jbtnPainelVenda;
    private javax.swing.JLabel jlblHora;
    private javax.swing.JLabel jlblLotusLogoIcon;
    private javax.swing.JLabel jlblOlhosdaLotusTitleBlue;
    private javax.swing.JLabel jlblOlhosdaLotusTitleDark;
    private javax.swing.JLabel jlblOlhosdaLotusTitleWhite;
    // End of variables declaration//GEN-END:variables
}
